name: Build and push to container registry

on:
  push:
    branches:
      - main

jobs:
  Publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub package registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create eureka properties file
        run: bash ./create_eureka_properties.sh ${{ secrets.EUREKA_USERNAME }} ${{ secrets.EUREKA_PASS }}

      - name: Create cognito properties file
        run: bash ./create_cognito_properties.sh ${{ secrets.COGNITO_REGION }} ${{ secrets.COGNITO_USER_POOL_ID }}

      - name: Build docker image
        run: docker build -t ghcr.io/roamly-gps-application/api-gateway:latest .

      - name: Push docker image
        run: docker push ghcr.io/roamly-gps-application/api-gateway:latest

      - name: Trigger release pipeline
        run: gh workflow run "deploy-to-test-server.yml" -R roamly-gps-application/roamly-release -f deploy_target=test --ref main